language: ruby
rvm:
- 2.1.2
before_script:
- git clone https://github.com/rodrigosiqueira/kuniri.git
- cd kuniri
- gem install yard
- gem install rspec
script:
- rake spec
notifications:
on_success: change
on_failure: always
