:language: ruby
:source: ./spec/samples/rubySyntaxParts/conditionalStatment/veryDeepConditionalStructure.rb
:output: ./spec/language/ruby/global_test/conditional/veryDeepConditionalStructure.xml
:extract: uml
