:language: ruby
:source: ./spec/samples/rubySyntaxParts/repetition/constructorWithVeryNestedRepetition.rb
:output: ./spec/language/ruby/global_test/repetition/constructorWithNestedRepetition.xml
:extract: uml
