:language: ruby
:source: ./spec/samples/rubySyntaxParts/repetition/methodWithVeryNestedRepetition.rb
:output: ./spec/language/ruby/global_test/repetition/methodWithVeryNestedRepetition.xml
:extract: uml
